[package]
name = "sniper"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.12"
rusty-machine = "0.5"
serde = "1"
serde_derive = "1"
rand = "0.8"
csv = "1"